In [1]:
import torch

In [2]:
import numpy as np

In [3]:
from torch.nn import Linear
myLayer = Linear(in_features=10, out_features=5, bias = True)

In [4]:
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10, out_features=5, bias=True)

NameError: name 'Variable' is not defined

In [5]:
myLayer.weight

Parameter containing:
tensor([[ 0.1157,  0.2912, -0.1971, -0.1063,  0.2417,  0.1738, -0.0403, -0.2970,
          0.0015, -0.0033],
        [ 0.1448,  0.2199, -0.1119,  0.1141,  0.2859, -0.3057,  0.1286, -0.1822,
          0.1428,  0.2856],
        [ 0.0365,  0.0097,  0.0893,  0.0616,  0.1952, -0.2311,  0.3135, -0.2043,
         -0.2261,  0.2912],
        [-0.1449,  0.0801, -0.0200, -0.0364,  0.1472,  0.0200, -0.0096,  0.2952,
         -0.0763,  0.1930],
        [-0.2673, -0.1072,  0.3106,  0.2654, -0.1348, -0.0568,  0.0452, -0.2812,
         -0.2521,  0.0631]], requires_grad=True)

In [6]:
myLayer.bias

Parameter containing:
tensor([ 0.0711, -0.0317, -0.3159, -0.1997, -0.2804], requires_grad=True)

In [7]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

NameError: name 'inp' is not defined

In [8]:
from torch.nn import ReLU
import torch

sample_data = torch.Tensor([1,2,-1,-1])
myRelu = ReLU()
myRelu(sample_data)

tensor([1., 2., 0., 0.])

In [11]:
import torch.nn as nn

In [25]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size, hidden_size, output_size):
        super(MyFirstNetwork,self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
        
    def forward(self,input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out

In [14]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5), requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input, target)
output.backward()

NameError: name 'Variable' is not defined

In [15]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1-prediction)